name: Deploy to GitHub Pages and Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy static site to GitHub Pages
  deploy-github-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile contracts
      run: npm run compile
      
    - name: Make build script executable
      run: chmod +x build-static.sh
      
    - name: Build static files for GitHub Pages
      run: ./build-static.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Test build for Vercel (Vercel will auto-deploy on push)
  test-vercel-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test Vercel build
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Test server start
      run: |
        timeout 10s npm start || true
        echo "✅ Server starts successfully"
